import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		int familyOfTwo = 0;
		int familyOfThree = 0;
		int familyOfFourPlus = 0;
		Double average = 0.0;
		for (int i = 0; i <T; i++ )
		{
			int childCount = 0;
			boolean boy = false;
			boolean girl = false;
			while( boy == false || girl == false )
			{
				double rand = generator.nextDouble();
				if (rand >= 0.5)
				{
					childCount++;
					boy = true;
					//System.out.print("b ");
				}
				else
				{				
					childCount++;
					girl = true;
					//System.out.print("g ");
				}				
			}
			average += childCount;
			switch (childCount) { // Adds to the static counter
				case 2:
					familyOfTwo++;
					break;
				case 3:
					familyOfThree++;
					break;
				default:
					familyOfFourPlus++;
					break;
			}
		}
		average /= T;
		System.out.println("Average: " + average + " children to get at least one of each gender."); 
		System.out.println("Number of families with 2 children: "+familyOfTwo);						
		System.out.println("Number of families with 3 children: "+familyOfThree);  					
		System.out.println("Number of families with 4 or more children: "+familyOfFourPlus);		
		// showing the correct message according to the category of families
		if (familyOfTwo > familyOfFourPlus){
			if (familyOfThree > familyOfTwo){
				System.out.println("The most common number of children is 3.");
			}
			else{
				System.out.println("The most common number of children is 2.");
			}
		}
		else{
			if (familyOfFourPlus > familyOfThree){
				System.out.println("The most common number of children is 4 or more.");
			}
			else{
				System.out.println("The most common number of children is 3.");
			}
		}
	}
}
